.TH "HTML\-CHAR" "7" "December 2016" "3" "CHEAT SHEET"
.SH "NAME"
\fBHTML-CHAR\fR \- HTML entity table
.SH TABLE
.P
you can use like \fB&gt;\fP to display \fB>\fP in HTML\. 
.TS
tab(|) expand box;
 l l l.
T{
Name
T}|T{
Character
T}|T{
Description
T}
_
T{
quot
T}|T{
"
T}|T{
quotation mark (APL quote)
T}
T{
amp
T}|T{
&
T}|T{
ampersand
T}
T{
apos
T}|T{
\|'
T}|T{
apostrophe (apostrophe\-quote); see below
T}
T{
lt
T}|T{
<
T}|T{
less\-than sign
T}
T{
gt
T}|T{
>
T}|T{
greater\-than sign
T}
T{
nbsp
T}|T{

T}|T{
no\-break space (non\-breaking space)[d]
T}
T{
iexcl
T}|T{
¡
T}|T{
inverted exclamation mark
T}
T{
cent
T}|T{
¢
T}|T{
cent sign
T}
T{
pound
T}|T{
£
T}|T{
pound sign
T}
T{
curren
T}|T{
¤
T}|T{
currency sign
T}
T{
yen
T}|T{
¥
T}|T{
yen sign (yuan sign)
T}
T{
brvbar
T}|T{
¦
T}|T{
broken bar (broken vertical bar)
T}
T{
sect
T}|T{
§
T}|T{
section sign
T}
T{
uml
T}|T{
¨
T}|T{
diaeresis (spacing diaeresis); see Germanic umlaut
T}
T{
copy
T}|T{
©
T}|T{
copyright symbol
T}
T{
ordf
T}|T{
ª
T}|T{
feminine ordinal indicator
T}
T{
laquo
T}|T{
«
T}|T{
left\-pointing double angle quotation mark (left pointing guillemet)
T}
T{
not
T}|T{
¬
T}|T{
not sign
T}
T{
shy
T}|T{

T}|T{
soft hyphen (discretionary hyphen)
T}
T{
reg
T}|T{
®
T}|T{
registered sign (registered trademark symbol)
T}
T{
macr
T}|T{
¯
T}|T{
macron (spacing macron, overline, APL overbar)
T}
T{
deg
T}|T{
°
T}|T{
degree symbol
T}
T{
plusmn
T}|T{
±
T}|T{
plus\-minus sign (plus\-or\-minus sign)
T}
T{
sup2
T}|T{
²
T}|T{
superscript two (superscript digit two, squared)
T}
T{
sup3
T}|T{
³
T}|T{
superscript three (superscript digit three, cubed)
T}
T{
acute
T}|T{
´
T}|T{
acute accent (spacing acute)
T}
T{
micro
T}|T{
µ
T}|T{
micro sign
T}
T{
para
T}|T{
¶
T}|T{
pilcrow sign (paragraph sign)
T}
T{
middot
T}|T{
·
T}|T{
middle dot (Georgian comma, Greek middle dot)
T}
T{
cedil
T}|T{
¸
T}|T{
cedilla (spacing cedilla)
T}
T{
sup1
T}|T{
¹
T}|T{
superscript one (superscript digit one)
T}
T{
ordm
T}|T{
º
T}|T{
masculine ordinal indicator
T}
T{
raquo
T}|T{
»
T}|T{
right\-pointing double angle quotation mark (right pointing guillemet)
T}
T{
frac14
T}|T{
¼
T}|T{
vulgar fraction one quarter (fraction one quarter)
T}
T{
frac12
T}|T{
½
T}|T{
vulgar fraction one half (fraction one half)
T}
T{
frac34
T}|T{
¾
T}|T{
vulgar fraction three quarters (fraction three quarters)
T}
T{
iquest
T}|T{
¿
T}|T{
inverted question mark (turned question mark)
T}
T{
Agrave
T}|T{
À
T}|T{
Latin capital letter A with grave accent (Latin capital letter A grave)
T}
T{
Aacute
T}|T{
Á
T}|T{
Latin capital letter A with acute accent
T}
T{
Acirc
T}|T{
Â
T}|T{
Latin capital letter A with circumflex
T}
T{
Atilde
T}|T{
Ã
T}|T{
Latin capital letter A with tilde
T}
T{
Auml
T}|T{
Ä
T}|T{
Latin capital letter A with diaeresis
T}
T{
Aring
T}|T{
Å
T}|T{
Latin capital letter A with ring above (Latin capital letter A ring)
T}
T{
AElig
T}|T{
Æ
T}|T{
Latin capital letter AE (Latin capital ligature AE)
T}
T{
Ccedil
T}|T{
Ç
T}|T{
Latin capital letter C with cedilla
T}
T{
Egrave
T}|T{
È
T}|T{
Latin capital letter E with grave accent
T}
T{
Eacute
T}|T{
É
T}|T{
Latin capital letter E with acute accent
T}
T{
Ecirc
T}|T{
Ê
T}|T{
Latin capital letter E with circumflex
T}
T{
Euml
T}|T{
Ë
T}|T{
Latin capital letter E with diaeresis
T}
T{
Igrave
T}|T{
Ì
T}|T{
Latin capital letter I with grave accent
T}
T{
Iacute
T}|T{
Í
T}|T{
Latin capital letter I with acute accent
T}
T{
Icirc
T}|T{
Î
T}|T{
Latin capital letter I with circumflex
T}
T{
Iuml
T}|T{
Ï
T}|T{
Latin capital letter I with diaeresis
T}
T{
ETH
T}|T{
Ð
T}|T{
Latin capital letter Eth
T}
T{
Ntilde
T}|T{
Ñ
T}|T{
Latin capital letter N with tilde
T}
T{
Ograve
T}|T{
Ò
T}|T{
Latin capital letter O with grave accent
T}
T{
Oacute
T}|T{
Ó
T}|T{
Latin capital letter O with acute accent
T}
T{
Ocirc
T}|T{
Ô
T}|T{
Latin capital letter O with circumflex
T}
T{
Otilde
T}|T{
Õ
T}|T{
Latin capital letter O with tilde
T}
T{
Ouml
T}|T{
Ö
T}|T{
Latin capital letter O with diaeresis
T}
T{
times
T}|T{
×
T}|T{
multiplication sign
T}
T{
Oslash
T}|T{
Ø
T}|T{
Latin capital letter O with stroke (Latin capital letter O slash)
T}
T{
Ugrave
T}|T{
Ù
T}|T{
Latin capital letter U with grave accent
T}
T{
Uacute
T}|T{
Ú
T}|T{
Latin capital letter U with acute accent
T}
T{
Ucirc
T}|T{
Û
T}|T{
Latin capital letter U with circumflex
T}
T{
Uuml
T}|T{
Ü
T}|T{
Latin capital letter U with diaeresis
T}
T{
Yacute
T}|T{
Ý
T}|T{
Latin capital letter Y with acute accent
T}
T{
THORN
T}|T{
Þ
T}|T{
Latin capital letter THORN
T}
T{
szlig
T}|T{
ß
T}|T{
Latin small letter sharp s (ess\-zed); see German Eszett
T}
T{
agrave
T}|T{
à
T}|T{
Latin small letter a with grave accent
T}
T{
aacute
T}|T{
á
T}|T{
Latin small letter a with acute accent
T}
T{
acirc
T}|T{
â
T}|T{
Latin small letter a with circumflex
T}
T{
atilde
T}|T{
ã
T}|T{
Latin small letter a with tilde
T}
T{
auml
T}|T{
ä
T}|T{
Latin small letter a with diaeresis
T}
T{
aring
T}|T{
å
T}|T{
Latin small letter a with ring above
T}
T{
aelig
T}|T{
æ
T}|T{
Latin small letter ae (Latin small ligature ae)
T}
T{
ccedil
T}|T{
ç
T}|T{
Latin small letter c with cedilla
T}
T{
egrave
T}|T{
è
T}|T{
Latin small letter e with grave accent
T}
T{
eacute
T}|T{
é
T}|T{
Latin small letter e with acute accent
T}
T{
ecirc
T}|T{
ê
T}|T{
Latin small letter e with circumflex
T}
T{
euml
T}|T{
ë
T}|T{
Latin small letter e with diaeresis
T}
T{
igrave
T}|T{
ì
T}|T{
Latin small letter i with grave accent
T}
T{
iacute
T}|T{
í
T}|T{
Latin small letter i with acute accent
T}
T{
icirc
T}|T{
î
T}|T{
Latin small letter i with circumflex
T}
T{
iuml
T}|T{
ï
T}|T{
Latin small letter i with diaeresis
T}
T{
eth
T}|T{
ð
T}|T{
Latin small letter eth
T}
T{
ntilde
T}|T{
ñ
T}|T{
Latin small letter n with tilde
T}
T{
ograve
T}|T{
ò
T}|T{
Latin small letter o with grave accent
T}
T{
oacute
T}|T{
ó
T}|T{
Latin small letter o with acute accent
T}
T{
ocirc
T}|T{
ô
T}|T{
Latin small letter o with circumflex
T}
T{
otilde
T}|T{
õ
T}|T{
Latin small letter o with tilde
T}
T{
ouml
T}|T{
ö
T}|T{
Latin small letter o with diaeresis
T}
T{
divide
T}|T{
÷
T}|T{
division sign (obelus)
T}
T{
oslash
T}|T{
ø
T}|T{
Latin small letter o with stroke (Latin small letter o slash)
T}
T{
ugrave
T}|T{
ù
T}|T{
Latin small letter u with grave accent
T}
T{
uacute
T}|T{
ú
T}|T{
Latin small letter u with acute accent
T}
T{
ucirc
T}|T{
û
T}|T{
Latin small letter u with circumflex
T}
T{
uuml
T}|T{
ü
T}|T{
Latin small letter u with diaeresis
T}
T{
yacute
T}|T{
ý
T}|T{
Latin small letter y with acute accent
T}
T{
thorn
T}|T{
þ
T}|T{
Latin small letter thorn
T}
T{
yuml
T}|T{
ÿ
T}|T{
Latin small letter y with diaeresis
T}
T{
OElig
T}|T{
Œ
T}|T{
Latin capital ligature oe[e]
T}
T{
oelig
T}|T{
œ
T}|T{
Latin small ligature oe[e]
T}
T{
Scaron
T}|T{
Š
T}|T{
Latin capital letter s with caron
T}
T{
scaron
T}|T{
š
T}|T{
Latin small letter s with caron
T}
T{
Yuml
T}|T{
Ÿ
T}|T{
Latin capital letter y with diaeresis
T}
T{
fnof
T}|T{
ƒ
T}|T{
Latin small letter f with hook (function, florin)
T}
T{
circ
T}|T{
ˆ
T}|T{
modifier letter circumflex accent
T}
T{
tilde
T}|T{
˜
T}|T{
small tilde
T}
T{
Alpha
T}|T{
Α
T}|T{
Greek capital letter Alpha
T}
T{
Beta
T}|T{
Β
T}|T{
Greek capital letter Beta
T}
T{
Gamma
T}|T{
Γ
T}|T{
Greek capital letter Gamma
T}
T{
Delta
T}|T{
Δ
T}|T{
Greek capital letter Delta
T}
T{
Epsilon
T}|T{
Ε
T}|T{
Greek capital letter Epsilon
T}
T{
Zeta
T}|T{
Ζ
T}|T{
Greek capital letter Zeta
T}
T{
Eta
T}|T{
Η
T}|T{
Greek capital letter Eta
T}
T{
Theta
T}|T{
Θ
T}|T{
Greek capital letter Theta
T}
T{
Iota
T}|T{
Ι
T}|T{
Greek capital letter Iota
T}
T{
Kappa
T}|T{
Κ
T}|T{
Greek capital letter Kappa
T}
T{
Lambda
T}|T{
Λ
T}|T{
Greek capital letter Lambda
T}
T{
Mu
T}|T{
Μ
T}|T{
Greek capital letter Mu
T}
T{
Nu
T}|T{
Ν
T}|T{
Greek capital letter Nu
T}
T{
Xi
T}|T{
Ξ
T}|T{
Greek capital letter Xi
T}
T{
Omicron
T}|T{
Ο
T}|T{
Greek capital letter Omicron
T}
T{
Pi
T}|T{
Π
T}|T{
Greek capital letter Pi
T}
T{
Rho
T}|T{
Ρ
T}|T{
Greek capital letter Rho
T}
T{
Sigma
T}|T{
Σ
T}|T{
Greek capital letter Sigma
T}
T{
Tau
T}|T{
Τ
T}|T{
Greek capital letter Tau
T}
T{
Upsilon
T}|T{
Υ
T}|T{
Greek capital letter Upsilon
T}
T{
Phi
T}|T{
Φ
T}|T{
Greek capital letter Phi
T}
T{
Chi
T}|T{
Χ
T}|T{
Greek capital letter Chi
T}
T{
Psi
T}|T{
Ψ
T}|T{
Greek capital letter Psi
T}
T{
Omega
T}|T{
Ω
T}|T{
Greek capital letter Omega
T}
T{
alpha
T}|T{
α
T}|T{
Greek small letter alpha
T}
T{
beta
T}|T{
β
T}|T{
Greek small letter beta
T}
T{
gamma
T}|T{
γ
T}|T{
Greek small letter gamma
T}
T{
delta
T}|T{
δ
T}|T{
Greek small letter delta
T}
T{
epsilon
T}|T{
ε
T}|T{
Greek small letter epsilon
T}
T{
zeta
T}|T{
ζ
T}|T{
Greek small letter zeta
T}
T{
eta
T}|T{
η
T}|T{
Greek small letter eta
T}
T{
theta
T}|T{
θ
T}|T{
Greek small letter theta
T}
T{
iota
T}|T{
ι
T}|T{
Greek small letter iota
T}
T{
kappa
T}|T{
κ
T}|T{
Greek small letter kappa
T}
T{
lambda
T}|T{
λ
T}|T{
Greek small letter lambda
T}
T{
mu
T}|T{
μ
T}|T{
Greek small letter mu
T}
T{
nu
T}|T{
ν
T}|T{
Greek small letter nu
T}
T{
xi
T}|T{
ξ
T}|T{
Greek small letter xi
T}
T{
omicron
T}|T{
ο
T}|T{
Greek small letter omicron
T}
T{
pi
T}|T{
π
T}|T{
Greek small letter pi
T}
T{
rho
T}|T{
ρ
T}|T{
Greek small letter rho
T}
T{
sigmaf
T}|T{
ς
T}|T{
Greek small letter final sigma
T}
T{
sigma
T}|T{
σ
T}|T{
Greek small letter sigma
T}
T{
tau
T}|T{
τ
T}|T{
Greek small letter tau
T}
T{
upsilon
T}|T{
υ
T}|T{
Greek small letter upsilon
T}
T{
phi
T}|T{
φ
T}|T{
Greek small letter phi
T}
T{
chi
T}|T{
χ
T}|T{
Greek small letter chi
T}
T{
psi
T}|T{
ψ
T}|T{
Greek small letter psi
T}
T{
omega
T}|T{
ω
T}|T{
Greek small letter omega
T}
T{
thetasym
T}|T{
ϑ
T}|T{
Greek theta symbol
T}
T{
upsih
T}|T{
ϒ
T}|T{
Greek Upsilon with hook symbol
T}
T{
piv
T}|T{
ϖ
T}|T{
Greek pi symbol
T}
T{
ensp
T}|T{
 
T}|T{
en space[d]
T}
T{
emsp
T}|T{
 
T}|T{
em space[d]
T}
T{
thinsp
T}|T{
 
T}|T{
thin space[d]
T}
T{
zwnj
T}|T{

T}|T{
zero\-width non\-joiner
T}
T{
zwj
T}|T{

T}|T{
zero\-width joiner
T}
T{
lrm
T}|T{

T}|T{
left\-to\-right mark
T}
T{
rlm
T}|T{

T}|T{
right\-to\-left mark
T}
T{
ndash
T}|T{
–
T}|T{
en dash
T}
T{
mdash
T}|T{
—
T}|T{
em dash
T}
T{
lsquo
T}|T{
‘
T}|T{
left single quotation mark
T}
T{
rsquo
T}|T{
’
T}|T{
right single quotation mark
T}
T{
sbquo
T}|T{
‚
T}|T{
single low\-9 quotation mark
T}
T{
ldquo
T}|T{
“
T}|T{
left double quotation mark
T}
T{
rdquo
T}|T{
”
T}|T{
right double quotation mark
T}
T{
bdquo
T}|T{
„
T}|T{
double low\-9 quotation mark
T}
T{
dagger
T}|T{
†
T}|T{
dagger, obelisk
T}
T{
Dagger
T}|T{
‡
T}|T{
double dagger, double obelisk
T}
T{
bull
T}|T{
•
T}|T{
bullet (black small circle)[f]
T}
T{
hellip
T}|T{
…
T}|T{
horizontal ellipsis (three dot leader)
T}
T{
permil
T}|T{
‰
T}|T{
per mille sign
T}
T{
prime
T}|T{
′
T}|T{
prime (minutes, feet)
T}
T{
Prime
T}|T{
″
T}|T{
double prime (seconds, inches)
T}
T{
lsaquo
T}|T{
‹
T}|T{
single left\-pointing angle quotation mark[g]
T}
T{
rsaquo
T}|T{
›
T}|T{
single right\-pointing angle quotation mark[g]
T}
T{
oline
T}|T{
‾
T}|T{
overline (spacing overscore)
T}
T{
frasl
T}|T{
⁄
T}|T{
fraction slash (solidus)
T}
T{
euro
T}|T{
€
T}|T{
euro sign
T}
T{
image
T}|T{
ℑ
T}|T{
black\-letter capital I (imaginary part)
T}
T{
weierp
T}|T{
℘
T}|T{
script capital P (power set, Weierstrass p)
T}
T{
real
T}|T{
ℜ
T}|T{
black\-letter capital R (real part symbol)
T}
T{
trade
T}|T{
™
T}|T{
trademark symbol
T}
T{
alefsym
T}|T{
ℵ
T}|T{
alef symbol (first transfinite cardinal)[h]
T}
T{
larr
T}|T{
←
T}|T{
leftwards arrow
T}
T{
uarr
T}|T{
↑
T}|T{
upwards arrow
T}
T{
rarr
T}|T{
→
T}|T{
rightwards arrow
T}
T{
darr
T}|T{
↓
T}|T{
downwards arrow
T}
T{
harr
T}|T{
↔
T}|T{
left right arrow
T}
T{
crarr
T}|T{
↵
T}|T{
downwards arrow with corner leftwards (carriage return)
T}
T{
lArr
T}|T{
⇐
T}|T{
leftwards double arrow[i]
T}
T{
uArr
T}|T{
⇑
T}|T{
upwards double arrow
T}
T{
rArr
T}|T{
⇒
T}|T{
rightwards double arrow[j]
T}
T{
dArr
T}|T{
⇓
T}|T{
downwards double arrow
T}
T{
hArr
T}|T{
⇔
T}|T{
left right double arrow
T}
T{
forall
T}|T{
∀
T}|T{
for all
T}
T{
part
T}|T{
∂
T}|T{
partial differential
T}
T{
exist
T}|T{
∃
T}|T{
there exists
T}
T{
empty
T}|T{
∅
T}|T{
empty set (null set); see also U+8960, ⌀
T}
T{
nabla
T}|T{
∇
T}|T{
del or nabla (vector differential operator)
T}
T{
isin
T}|T{
∈
T}|T{
element of
T}
T{
notin
T}|T{
∉
T}|T{
not an element of
T}
T{
ni
T}|T{
∋
T}|T{
contains as member
T}
T{
prod
T}|T{
∏
T}|T{
n\-ary product (product sign)[k]
T}
T{
sum
T}|T{
∑
T}|T{
n\-ary summation[l]
T}
T{
minus
T}|T{
−
T}|T{
minus sign
T}
T{
lowast
T}|T{
∗
T}|T{
asterisk operator
T}
T{
radic
T}|T{
√
T}|T{
square root (radical sign)
T}
T{
prop
T}|T{
∝
T}|T{
proportional to
T}
T{
infin
T}|T{
∞
T}|T{
infinity
T}
T{
ang
T}|T{
∠
T}|T{
angle
T}
T{
and
T}|T{
∧
T}|T{
logical and (wedge)
T}
T{
or
T}|T{
∨
T}|T{
logical or (vee)
T}
T{
cap
T}|T{
∩
T}|T{
intersection (cap)
T}
T{
cup
T}|T{
∪
T}|T{
union (cup)
T}
T{
int
T}|T{
∫
T}|T{
integral
T}
T{
there4
T}|T{
∴
T}|T{
therefore sign
T}
T{
sim
T}|T{
∼
T}|T{
tilde operator (varies with, similar to)[m]
T}
T{
cong
T}|T{
≅
T}|T{
congruent to
T}
T{
asymp
T}|T{
≈
T}|T{
almost equal to (asymptotic to)
T}
T{
ne
T}|T{
≠
T}|T{
not equal to
T}
T{
equiv
T}|T{
≡
T}|T{
identical to; sometimes used for 'equivalent to'
T}
T{
le
T}|T{
≤
T}|T{
less\-than or equal to
T}
T{
ge
T}|T{
≥
T}|T{
greater\-than or equal to
T}
T{
sub
T}|T{
⊂
T}|T{
subset of
T}
T{
sup
T}|T{
⊃
T}|T{
superset of[n]
T}
T{
nsub
T}|T{
⊄
T}|T{
not a subset of
T}
T{
sube
T}|T{
⊆
T}|T{
subset of or equal to
T}
T{
supe
T}|T{
⊇
T}|T{
superset of or equal to
T}
T{
oplus
T}|T{
⊕
T}|T{
circled plus (direct sum)
T}
T{
otimes
T}|T{
⊗
T}|T{
circled times (vector product)
T}
T{
perp
T}|T{
⊥
T}|T{
up tack (orthogonal to, perpendicular)[o]
T}
T{
sdot
T}|T{
⋅
T}|T{
dot operator[p]
T}
T{
lceil
T}|T{
⌈
T}|T{
left ceiling (APL upstile)
T}
T{
rceil
T}|T{
⌉
T}|T{
right ceiling
T}
T{
lfloor
T}|T{
⌊
T}|T{
left floor (APL downstile)
T}
T{
rfloor
T}|T{
⌋
T}|T{
right floor
T}
T{
lang
T}|T{
⟨
T}|T{
left\-pointing angle bracket (bra)[q]
T}
T{
rang
T}|T{
⟩
T}|T{
right\-pointing angle bracket (ket)[r]
T}
T{
loz
T}|T{
◊
T}|T{
lozenge
T}
T{
spades
T}|T{
♠
T}|T{
black spade suit[f]
T}
T{
clubs
T}|T{
♣
T}|T{
black club suit (shamrock)[f]
T}
T{
hearts
T}|T{
♥
T}|T{
black heart suit (valentine)[f]
T}
T{
diams
T}|T{
♦
T}|T{
black diamond suit[f]
T}
.TE
.TS
tab(|) expand box;
 l l l l l.
T{
Name
T}|T{
Unicode code point (decimal)
T}|T{
Standard
T}|T{
DTD[a]
T}|T{
Old ISO subset[b]
T}
_
T{
quot
T}|T{
U+0022 (34)
T}|T{
HTML 2\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
amp
T}|T{
U+0026 (38)
T}|T{
HTML 2\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
apos
T}|T{
U+0027 (39)
T}|T{
XHTML 1\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
lt
T}|T{
U+003C (60)
T}|T{
HTML 2\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
gt
T}|T{
U+003E (62)
T}|T{
HTML 2\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
nbsp
T}|T{
U+00A0 (160)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
iexcl
T}|T{
U+00A1 (161)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
cent
T}|T{
U+00A2 (162)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
pound
T}|T{
U+00A3 (163)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
curren
T}|T{
U+00A4 (164)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
yen
T}|T{
U+00A5 (165)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
brvbar
T}|T{
U+00A6 (166)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
sect
T}|T{
U+00A7 (167)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
uml
T}|T{
U+00A8 (168)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOdia
T}
T{
copy
T}|T{
U+00A9 (169)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
ordf
T}|T{
U+00AA (170)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
laquo
T}|T{
U+00AB (171)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
not
T}|T{
U+00AC (172)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
shy
T}|T{
U+00AD (173)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
reg
T}|T{
U+00AE (174)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
macr
T}|T{
U+00AF (175)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOdia
T}
T{
deg
T}|T{
U+00B0 (176)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
plusmn
T}|T{
U+00B1 (177)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
sup2
T}|T{
U+00B2 (178)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
sup3
T}|T{
U+00B3 (179)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
acute
T}|T{
U+00B4 (180)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOdia
T}
T{
micro
T}|T{
U+00B5 (181)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
para
T}|T{
U+00B6 (182)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
middot
T}|T{
U+00B7 (183)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
cedil
T}|T{
U+00B8 (184)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOdia
T}
T{
sup1
T}|T{
U+00B9 (185)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
ordm
T}|T{
U+00BA (186)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
raquo
T}|T{
U+00BB (187)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
frac14
T}|T{
U+00BC (188)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
frac12
T}|T{
U+00BD (189)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
frac34
T}|T{
U+00BE (190)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
iquest
T}|T{
U+00BF (191)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
Agrave
T}|T{
U+00C0 (192)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Aacute
T}|T{
U+00C1 (193)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Acirc
T}|T{
U+00C2 (194)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Atilde
T}|T{
U+00C3 (195)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Auml
T}|T{
U+00C4 (196)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Aring
T}|T{
U+00C5 (197)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
AElig
T}|T{
U+00C6 (198)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Ccedil
T}|T{
U+00C7 (199)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Egrave
T}|T{
U+00C8 (200)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Eacute
T}|T{
U+00C9 (201)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Ecirc
T}|T{
U+00CA (202)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Euml
T}|T{
U+00CB (203)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Igrave
T}|T{
U+00CC (204)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Iacute
T}|T{
U+00CD (205)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Icirc
T}|T{
U+00CE (206)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Iuml
T}|T{
U+00CF (207)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ETH
T}|T{
U+00D0 (208)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Ntilde
T}|T{
U+00D1 (209)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Ograve
T}|T{
U+00D2 (210)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Oacute
T}|T{
U+00D3 (211)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Ocirc
T}|T{
U+00D4 (212)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Otilde
T}|T{
U+00D5 (213)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Ouml
T}|T{
U+00D6 (214)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
times
T}|T{
U+00D7 (215)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
Oslash
T}|T{
U+00D8 (216)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Ugrave
T}|T{
U+00D9 (217)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Uacute
T}|T{
U+00DA (218)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Ucirc
T}|T{
U+00DB (219)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Uuml
T}|T{
U+00DC (220)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
Yacute
T}|T{
U+00DD (221)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
THORN
T}|T{
U+00DE (222)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
szlig
T}|T{
U+00DF (223)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
agrave
T}|T{
U+00E0 (224)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
aacute
T}|T{
U+00E1 (225)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
acirc
T}|T{
U+00E2 (226)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
atilde
T}|T{
U+00E3 (227)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
auml
T}|T{
U+00E4 (228)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
aring
T}|T{
U+00E5 (229)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
aelig
T}|T{
U+00E6 (230)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ccedil
T}|T{
U+00E7 (231)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
egrave
T}|T{
U+00E8 (232)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
eacute
T}|T{
U+00E9 (233)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ecirc
T}|T{
U+00EA (234)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
euml
T}|T{
U+00EB (235)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
igrave
T}|T{
U+00EC (236)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
iacute
T}|T{
U+00ED (237)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
icirc
T}|T{
U+00EE (238)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
iuml
T}|T{
U+00EF (239)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
eth
T}|T{
U+00F0 (240)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ntilde
T}|T{
U+00F1 (241)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ograve
T}|T{
U+00F2 (242)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
oacute
T}|T{
U+00F3 (243)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ocirc
T}|T{
U+00F4 (244)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
otilde
T}|T{
U+00F5 (245)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ouml
T}|T{
U+00F6 (246)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
divide
T}|T{
U+00F7 (247)
T}|T{
HTML 3\.2
T}|T{
HTMLlat1
T}|T{
ISOnum
T}
T{
oslash
T}|T{
U+00F8 (248)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ugrave
T}|T{
U+00F9 (249)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
uacute
T}|T{
U+00FA (250)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
ucirc
T}|T{
U+00FB (251)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
uuml
T}|T{
U+00FC (252)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
yacute
T}|T{
U+00FD (253)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
thorn
T}|T{
U+00FE (254)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
yuml
T}|T{
U+00FF (255)
T}|T{
HTML 2\.0
T}|T{
HTMLlat1
T}|T{
ISOlat1
T}
T{
OElig
T}|T{
U+0152 (338)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOlat2
T}
T{
oelig
T}|T{
U+0153 (339)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOlat2
T}
T{
Scaron
T}|T{
U+0160 (352)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOlat2
T}
T{
scaron
T}|T{
U+0161 (353)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOlat2
T}
T{
Yuml
T}|T{
U+0178 (376)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOlat2
T}
T{
fnof
T}|T{
U+0192 (402)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
circ
T}|T{
U+02C6 (710)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
tilde
T}|T{
U+02DC (732)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOdia
T}
T{
Alpha
T}|T{
U+0391 (913)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Beta
T}|T{
U+0392 (914)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Gamma
T}|T{
U+0393 (915)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Delta
T}|T{
U+0394 (916)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Epsilon
T}|T{
U+0395 (917)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Zeta
T}|T{
U+0396 (918)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Eta
T}|T{
U+0397 (919)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Theta
T}|T{
U+0398 (920)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Iota
T}|T{
U+0399 (921)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Kappa
T}|T{
U+039A (922)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Lambda
T}|T{
U+039B (923)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Mu
T}|T{
U+039C (924)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Nu
T}|T{
U+039D (925)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Xi
T}|T{
U+039E (926)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Omicron
T}|T{
U+039F (927)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Pi
T}|T{
U+03A0 (928)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Rho
T}|T{
U+03A1 (929)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Sigma
T}|T{
U+03A3 (931)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Tau
T}|T{
U+03A4 (932)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Upsilon
T}|T{
U+03A5 (933)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Phi
T}|T{
U+03A6 (934)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Chi
T}|T{
U+03A7 (935)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{

T}
T{
Psi
T}|T{
U+03A8 (936)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
Omega
T}|T{
U+03A9 (937)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
alpha
T}|T{
U+03B1 (945)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
beta
T}|T{
U+03B2 (946)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
gamma
T}|T{
U+03B3 (947)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
delta
T}|T{
U+03B4 (948)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
epsilon
T}|T{
U+03B5 (949)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
zeta
T}|T{
U+03B6 (950)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
eta
T}|T{
U+03B7 (951)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
theta
T}|T{
U+03B8 (952)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
iota
T}|T{
U+03B9 (953)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
kappa
T}|T{
U+03BA (954)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
lambda
T}|T{
U+03BB (955)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
mu
T}|T{
U+03BC (956)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
nu
T}|T{
U+03BD (957)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
xi
T}|T{
U+03BE (958)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
omicron
T}|T{
U+03BF (959)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
NEW
T}
T{
pi
T}|T{
U+03C0 (960)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
rho
T}|T{
U+03C1 (961)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
sigmaf
T}|T{
U+03C2 (962)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
sigma
T}|T{
U+03C3 (963)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
tau
T}|T{
U+03C4 (964)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
upsilon
T}|T{
U+03C5 (965)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
phi
T}|T{
U+03C6 (966)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
chi
T}|T{
U+03C7 (967)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
psi
T}|T{
U+03C8 (968)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
omega
T}|T{
U+03C9 (969)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
thetasym
T}|T{
U+03D1 (977)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
NEW
T}
T{
upsih
T}|T{
U+03D2 (978)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
NEW
T}
T{
piv
T}|T{
U+03D6 (982)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOgrk3
T}
T{
ensp
T}|T{
U+2002 (8194)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
emsp
T}|T{
U+2003 (8195)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
thinsp
T}|T{
U+2009 (8201)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
zwnj
T}|T{
U+200C (8204)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
NEW RFC 2070
T}
T{
zwj
T}|T{
U+200D (8205)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
NEW RFC 2070
T}
T{
lrm
T}|T{
U+200E (8206)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
NEW RFC 2070
T}
T{
rlm
T}|T{
U+200F (8207)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
NEW RFC 2070
T}
T{
ndash
T}|T{
U+2013 (8211)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
mdash
T}|T{
U+2014 (8212)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
lsquo
T}|T{
U+2018 (8216)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
rsquo
T}|T{
U+2019 (8217)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
sbquo
T}|T{
U+201A (8218)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
NEW
T}
T{
ldquo
T}|T{
U+201C (8220)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
rdquo
T}|T{
U+201D (8221)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOnum
T}
T{
bdquo
T}|T{
U+201E (8222)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
NEW
T}
T{
dagger
T}|T{
U+2020 (8224)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
Dagger
T}|T{
U+2021 (8225)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
bull
T}|T{
U+2022 (8226)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOpub
T}
T{
hellip
T}|T{
U+2026 (8230)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOpub
T}
T{
permil
T}|T{
U+2030 (8240)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISOtech
T}
T{
prime
T}|T{
U+2032 (8242)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
Prime
T}|T{
U+2033 (8243)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
lsaquo
T}|T{
U+2039 (8249)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISO proposed
T}
T{
rsaquo
T}|T{
U+203A (8250)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
ISO proposed
T}
T{
oline
T}|T{
U+203E (8254)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
NEW
T}
T{
frasl
T}|T{
U+2044 (8260)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
NEW
T}
T{
euro
T}|T{
U+20AC (8364)
T}|T{
HTML 4\.0
T}|T{
HTMLspecial
T}|T{
NEW
T}
T{
image
T}|T{
U+2111 (8465)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamso
T}
T{
weierp
T}|T{
U+2118 (8472)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamso
T}
T{
real
T}|T{
U+211C (8476)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamso
T}
T{
trade
T}|T{
U+2122 (8482)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOnum
T}
T{
alefsym
T}|T{
U+2135 (8501)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
NEW
T}
T{
larr
T}|T{
U+2190 (8592)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOnum
T}
T{
uarr
T}|T{
U+2191 (8593)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOnum
T}
T{
rarr
T}|T{
U+2192 (8594)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOnum
T}
T{
darr
T}|T{
U+2193 (8595)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOnum
T}
T{
harr
T}|T{
U+2194 (8596)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsa
T}
T{
crarr
T}|T{
U+21B5 (8629)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
NEW
T}
T{
lArr
T}|T{
U+21D0 (8656)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
uArr
T}|T{
U+21D1 (8657)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsa
T}
T{
rArr
T}|T{
U+21D2 (8658)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOnum
T}
T{
dArr
T}|T{
U+21D3 (8659)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsa
T}
T{
hArr
T}|T{
U+21D4 (8660)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsa
T}
T{
forall
T}|T{
U+2200 (8704)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
part
T}|T{
U+2202 (8706)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
exist
T}|T{
U+2203 (8707)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
empty
T}|T{
U+2205 (8709)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamso
T}
T{
nabla
T}|T{
U+2207 (8711)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
isin
T}|T{
U+2208 (8712)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
notin
T}|T{
U+2209 (8713)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
ni
T}|T{
U+220B (8715)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
prod
T}|T{
U+220F (8719)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsb
T}
T{
sum
T}|T{
U+2211 (8721)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsb
T}
T{
minus
T}|T{
U+2212 (8722)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
lowast
T}|T{
U+2217 (8727)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
radic
T}|T{
U+221A (8730)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
prop
T}|T{
U+221D (8733)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
infin
T}|T{
U+221E (8734)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
ang
T}|T{
U+2220 (8736)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamso
T}
T{
and
T}|T{
U+2227 (8743)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
or
T}|T{
U+2228 (8744)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
cap
T}|T{
U+2229 (8745)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
cup
T}|T{
U+222A (8746)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
int
T}|T{
U+222B (8747)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
there4
T}|T{
U+2234 (8756)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
sim
T}|T{
U+223C (8764)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
cong
T}|T{
U+2245 (8773)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
asymp
T}|T{
U+2248 (8776)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsr
T}
T{
ne
T}|T{
U+2260 (8800)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
equiv
T}|T{
U+2261 (8801)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
le
T}|T{
U+2264 (8804)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
ge
T}|T{
U+2265 (8805)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
sub
T}|T{
U+2282 (8834)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
sup
T}|T{
U+2283 (8835)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
nsub
T}|T{
U+2284 (8836)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsn
T}
T{
sube
T}|T{
U+2286 (8838)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
supe
T}|T{
U+2287 (8839)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
oplus
T}|T{
U+2295 (8853)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsb
T}
T{
otimes
T}|T{
U+2297 (8855)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsb
T}
T{
perp
T}|T{
U+22A5 (8869)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
sdot
T}|T{
U+22C5 (8901)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsb
T}
T{
lceil
T}|T{
U+2308 (8968)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsc
T}
T{
rceil
T}|T{
U+2309 (8969)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsc
T}
T{
lfloor
T}|T{
U+230A (8970)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsc
T}
T{
rfloor
T}|T{
U+230B (8971)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOamsc
T}
T{
lang
T}|T{
U+2329 (9001)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
rang
T}|T{
U+232A (9002)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOtech
T}
T{
loz
T}|T{
U+25CA (9674)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOpub
T}
T{
spades
T}|T{
U+2660 (9824)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOpub
T}
T{
clubs
T}|T{
U+2663 (9827)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOpub
T}
T{
hearts
T}|T{
U+2665 (9829)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOpub
T}
T{
diams
T}|T{
U+2666 (9830)
T}|T{
HTML 4\.0
T}|T{
HTMLsymbol
T}|T{
ISOpub
T}
T{

T}
.TE
.SH VERSION
.RS 0
.IP 1. 3
copy and paste from wiki, use pure text\. 
.IP 2. 3
use troff tbl macro\. 
.IP 3. 3
use markdown and marked\-man\.

.RE
.SH SEE ALSO: CHEAT SHEET
.P
groff\-char(7) 
.SH REPORT BUG
.P
85619andy@gmail\.com

