.mso zh.tmac
.TH "TANET" "7" "January 2018" "" "NCKU CCNS"
.SH "NAME"
\fBTANet\fR \- 台灣學術網路
.SH DESCRIPTION
.P
\fBTANet\fR 為 \fITaiwan Academic Network\fR ，即台灣學術網路，
為中華民國教育部與台灣各大學共同建立的
一個全國性教學研究用網際網路系統。
.SH HISTORY
.P
1980 年代中期，教育部引進 BITNET 大學教學研究網路系統，提供
學術界跨國電子 郵件、檔案傳輸等應用服務。1980 年代末期，
教育部科技顧問室（1990 年更名為 顧問室）在張進福主任任內
編列經費，委由科技顧問陳文村規劃，補助主要國立 大學建立
校園網路、校際網路。於 1990 年 7 月，教育部電子計算機中心邀集
受補助大學成立「台灣學術網路」，建立以 TCP/IP 通訊協定為基礎
之網際網路系統， 為台灣第一個網際網路系統， 也是台灣往後
發展政府、商用網際網路系統之基礎 。1999 年起，教育部推動
中小學使用 ADSL 連線至 TANet，讓資訊教育向下扎根， 迄今 TANet
已成為全台灣各級學校網路及資訊教育之平台。
.P
TANet 初期連接台灣部份的學術單位與研究機構，網路骨幹使用電話
連線，頻寬 為 9\.6kbps。1991 年 12 月 3 日以 64Kbps 數據專線連接美國
普林斯頓大學的 JvNCnet，成為台灣的第一條跨國網路連線。1994
年年初，以 T1 連接架設中的 Hinet，成 為台灣第一條網際網路對等
連線（peering），台灣的網際網路正式進入跨網時 代。同年 6 月以
10Mbps 的乙太網路連接 SEEDNet，台灣開始了多網系統的網網相連 。
歷經多年來擴充，TANet 網路架構分為國家骨幹網路、地區性網路、
校園網路 三個階層，2005 年 TANet 國家骨幹網路全面提昇至 10GE 之
網路環境。截至 2008 年 4 月，連美國頻寬為 STM16(2488\.32Mbps)，
連台灣其它網路總頻寬達 102\.718Gbps。
.P
TANet 的管理組織分為三個階層：「台灣學術網路管理委員會」、
「區域網路中心推動小組」以及「縣市教育網路中心推動小組」。
.SH 架構
.P
TANet 在全國各區域選出一個院校單位，成立區域網路中心，
協助該區域內相關學校及學術研究單位共享網際網路資源。
.RS 0
.IP 1. 3
台北區域網路中心：
.RS
.IP \(bu 2
台灣大學計資中心
.IP \(bu 2
政治大學電算中心

.RE
.IP 2. 3
桃園區域網路中心：中央大學電算中心
.IP 3. 3
竹苗區域網路中心：
.RS
.IP \(bu 2
交通大學資訊技術服務中心
.IP \(bu 2
清華大學計通中心

.RE
.IP 4. 3
台中區域網路中心：中興大學電算中心
.IP 5. 3
南投區域網路中心：暨南大學電算中心
.IP 6. 3
雲嘉區域網路中心：中正大學電算中心
.IP 7. 3
台南區域網路中心：成功大學電算中心
.IP 8. 3
高屏澎區域網路中心：中山大學電算中心
.IP 9. 3
花蓮區域網路中心：東華大學資訊與網路中心
（花蓮區網中心與花東區網中心於 2009 年 1 月 19 日合併）
.IP 10. 3
台東區域網路中心：台東大學電算中心

.RE
.SH 網域命名規則
.RS 0
.IP 1. 3
大專以上院校，以兩個英文字母以上簡稱縮寫，附加 edu\.tw。
如 ntu\.edu\.tw 為國立台灣大學的網域名。
.IP 2. 3
高中職若有英文名稱則沿用之，附加縣市 domain\.edu\.tw。
如高雄市立高雄高級中學英文名為 kshs，網域名為
kshs\.kh\.edu\.tw；國立科學工業園區實驗高級中學英文名為
nehs，網域名為 nehs\.hc\.edu\.tw。其他依下述規則命名：
.RS
.IP 1. 3
高級中學：校名縮寫英文字母+hs\.縣市 domain\.edu\.tw
.IP 2. 3
完全中學（分國中部、高中部的學校）：
校名縮寫英文字母+sh\.縣市 domain\.edu\.tw
.IP 3. 3
職業學校：校名縮寫英文字母+vs\.縣市 domain\.edu\.tw
.IP 4. 3
若高工高商家商商工的縮寫名稱過長，依狀況決定。

.RE

.RE
.RS 0
.IP 1. 3
女子高中依下面二種方式命名：
.RS
.IP 1. 3
校名縮寫英文字母+gsh\.縣市 domain\.edu\.tw
.IP 2. 3
校名縮寫英文字母+gs\.縣市 domain\.edu\.tw

.RE

.RE
.RS 0
.IP 1. 3
國民中學：校名縮寫英文字母+jh\.縣市 domain\.edu\.tw
.IP 2. 3
國民小學依下面二種方式命名：
.RS
.IP 1. 3
校名縮寫英文字母+ps\.縣市 domain\.edu\.tw
.IP 2. 3
校名縮寫英文字母+es\.縣市 domain\.edu\.tw

.RE
.IP 3. 3
國中小：校名縮寫英文字母+jps\.縣市 domain\.edu\.tw
.IP 4. 3
幼稚園：校名縮寫英文字母+kg\.縣市 domain\.edu\.tw

.RE
.SH IP 位址範圍
.P
IP 位址的分配依亞太網路資訊中心（APNIC）與台灣網路資訊
中心（TWNIC）的規範。TANet 多數 IP 開頭為 140\.92、140\.109
至 140\.138，尚有 192\.83、192\.192 與 163\.13 至 163\.28，其中
163\.28 保留作為 TANet 及區網 Proxy 專用網段。網域名多以
edu\.tw 結束，部份單位有獨立網域名。
.SS 大專院校的 IP
.TS
tab(|) expand nowarn box;
 l l.
T{
ip
T}|T{
大學 
T}
_
T{
 140\.112
T}|T{
國立臺灣大學 
T}
T{
 140\.113
T}|T{
國立交通大學 
T}
T{
 140\.114
T}|T{
國立清華大學 
T}
T{
 140\.115
T}|T{
國立中央大學 
T}
T{
 140\.116
T}|T{
國立成功大學 
T}
T{
 140\.117
T}|T{
國立中山大學 
T}
T{
 140\.118
T}|T{
國立台灣科技大學 
T}
T{
 140\.119
T}|T{
國立政治大學 
T}
T{
 140\.120
T}|T{
國立中興大學 
T}
T{
 140\.121
T}|T{
國立台灣海洋大學 
T}
T{
 140\.122
T}|T{
國立台灣師範大學 
T}
T{
 140\.123
T}|T{
國立中正大學 
T}
T{
 140\.124
T}|T{
國立台北科技大學 
T}
T{
 140\.125
T}|T{
國立雲林科技大學 
T}
T{
 140\.126\.3~21
T}|T{
中華大學 
T}
T{
 140\.126\.22~23,
T}|T{
國立新竹教育大學 
T}
T{
 140\.126\.29~47
T}|T{
國立新竹教育大學
T}
T{
 140\.127\.1~35
T}|T{
國立屏東科技大學 
T}
T{
 140\.127\.36~80
T}|T{
國立高雄師範大學 
T}
T{
 140\.127\.81~85
T}|T{
國立屏東教育大學 
T}
T{
 140\.127\.86~110
T}|T{
輔英科技大學 
T}
T{
 140\.127\.111~120,
T}|T{
國立高雄應用科技大學 
T}
T{
 140\.127\.149~150,
T}|T{
國立高雄應用科技大學 
T}
T{
 140\.133\.64~93
T}|T{
國立高雄應用科技大學 
T}
T{
 140\.127\.121~140
T}|T{
正修科技大學 
T}
T{
 140\.127\.149~160
T}|T{
空軍官校 
T}
T{
 140\.127\.164~170
T}|T{
文藻外語大學 
T}
T{
 140\.127\.171~175
T}|T{
國立台東大學 
T}
T{
 140\.127\.176~191
T}|T{
義守大學 
T}
T{
 140\.127\.198~234,
T}|T{
國立高雄大學 
T}
T{
 140\.133\.32~63
T}|T{
國立高雄大學 
T}
T{
 140\.128\.1~40
T}|T{
靜宜大學 
T}
T{
 140\.128\.41~60
T}|T{
南開科技大學 
T}
T{
 140\.128\.61~70
T}|T{
中國醫藥大學 
T}
T{
 140\.128\.71~95
T}|T{
國立勤益科技大學 
T}
T{
 140\.128\.96~135
T}|T{
東海大學 
T}
T{
 140\.128\.136~147
T}|T{
中山醫學大學 
T}
T{
 140\.128\.148~151
T}|T{
中臺科技大學 
T}
T{
 140\.129\.1~50
T}|T{
大同大學 
T}
T{
 140\.129\.51~80
T}|T{
國立陽明大學 
T}
T{
 140\.129\.81~85
T}|T{
台北海洋技術學院 
T}
T{
 140\.129\.86~115,140\.132
T}|T{
國防大學 
T}
T{
 140\.129\.116~145
T}|T{
東南科技大學 
T}
T{
 140\.130\.1~40
T}|T{
國立虎尾科技大學 
T}
T{
 140\.130\.41~50
T}|T{
國立嘉義大學 
T}
T{
 140\.130\.81~100
T}|T{
國立嘉義大學 
T}
T{
 140\.130\.101~130
T}|T{
吳鳳科技大學 
T}
T{
 140\.130\.131~150
T}|T{
大同技術學院 
T}
T{
 140\.130\.151~168
T}|T{
環球科技大學 
T}
T{
 140\.131\.1~20
T}|T{
龍華科技大學 
T}
T{
 140\.131\.21~30
T}|T{
國立台灣藝術大學 
T}
T{
 140\.131\.31~40
T}|T{
華夏科技大學 
T}
T{
 140\.131\.45~76
T}|T{
銘傳大學 
T}
T{
 140\.131\.77~84
T}|T{
致理技術學院 
T}
T{
 140\.131\.85~95
T}|T{
國立臺北護理健康大學 
T}
T{
 140\.133\.1~15
T}|T{
國立臺南大學 
T}
T{
 140\.134
T}|T{
逢甲大學 
T}
T{
 140\.135
T}|T{
中原大學 
T}
T{
 140\.136
T}|T{
天主教輔仁大學 
T}
T{
 140\.137
T}|T{
中國文化大學 
T}
T{
 140\.138
T}|T{
元智大學 
T}
T{
 134\.208
T}|T{
國立東華大學 
T}
T{
 163\.13
T}|T{
淡江大學 
T}
T{
 163\.14
T}|T{
東吳大學 
T}
T{
 163\.15\.1~23
T}|T{
陸軍軍官學校 
T}
T{
 163\.15\.151~180
T}|T{
高雄醫學大學 
T}
T{
 163\.17\.131~145
T}|T{
國立臺中科技大學 
T}
T{
 163\.18
T}|T{
國立高雄第一科技大學 
T}
T{
 163\.20\.144
T}|T{
新北市立清水高中 
T}
T{
 163\.20\.180
T}|T{
新北高中 
T}
T{
 163\.21\.98
T}|T{
耕莘健康管理專科學校 
T}
T{
 163\.21\.236
T}|T{
臺北市立大學 
T}
T{
 163\.22
T}|T{
國立暨南國際大學 
T}
T{
 192\.83\.167
T}|T{
國立臺中教育大學 
T}
T{
 192\.83\.170~185
T}|T{
國立臺北大學 
T}
T{
 192\.192\.35~36
T}|T{
國立臺北大學 
T}
T{
 192\.83\.172
T}|T{
國立臺中科技大學 
T}
T{
 192\.83\.173
T}|T{
國立彰化師範大學 
T}
T{
 192\.83\.174
T}|T{
大葉大學 
T}
T{
 192\.83\.179
T}|T{
國立臺北教育大學 
T}
T{
 192\.83\.181
T}|T{
國立體育大學 
T}
T{
 192\.83\.182
T}|T{
興國管理學院 
T}
T{
 192\.83\.183
T}|T{
國立宜蘭大學 
T}
T{
 192\.83\.190
T}|T{
高苑科技大學 
T}
T{
 192\.83\.193
T}|T{
實踐大學 
T}
T{
 192\.83\.194~195
T}|T{
國立高雄海洋科技大學 
T}
T{
 192\.192\.1
T}|T{
中央警察大學 
T}
T{
 192\.192\.2
T}|T{
嶺東科技大學 
T}
T{
 192\.192\.3
T}|T{
台南應用科技大學 
T}
T{
 192\.192\.30~32
T}|T{
崑山科技大學 
T}
T{
 192\.192\.37~39
T}|T{
南台科技大學 
T}
T{
 192\.192\.40~43
T}|T{
萬能科技大學 
T}
T{
 192\.192\.44
T}|T{
景文科技大學 
T}
T{
 192\.192\.45
T}|T{
嘉南藥理大學 
T}
T{
 192\.192\.48~55
T}|T{
國立空中大學 
T}
T{
 192\.192\.56~57
T}|T{
健行科技大學 
T}
T{
 192\.192\.60~67
T}|T{
長庚大學 
T}
T{
 192\.192\.68~73
T}|T{
亞東技術學院 
T}
T{
 192\.192\.74~77
T}|T{
黎明技術學院 
T}
T{
 192\.192\.78~85
T}|T{
中國科技大學 
T}
T{
 192\.192\.125~129
T}|T{
僑光科技大學 
T}
T{
 192\.192\.132~133
T}|T{
明志科技大學 
T}
T{
 192\.192\.139
T}|T{
國立臺灣體育運動大學 
T}
T{
 192\.192\.140~141
T}|T{
德明財經科技大學 
T}
T{
 192\.192\.148~159
T}|T{
世新大學 
T}
T{
 192\.192\.230
T}|T{
中華科技大學 
T}
T{
 120\.96\.32~79
T}|T{
亞東技術學院 
T}
T{
 120\.107\.144~215
T}|T{
國立彰化師範大學 
T}
T{
 120\.109\.0~79
T}|T{
建國科技大學 
T}
T{
 120\.109\.160~191
T}|T{
修平科技大學 
T}
T{
 120\.110
T}|T{
靜宜大學 (主要 140\.128\.1~40)
T}
T{
 120\.113\.64~127
T}|T{
國立虎尾科技大學 
T}
T{
 120\.119
T}|T{
樹德科技大學 
T}
T{
 120\.124
T}|T{
健行科技大學 
T}
T{
 120\.125\.86
T}|T{
銘傳大學 
T}
T{
 120\.125\.96~111
T}|T{
國立金門大學 
T}
T{
 120\.126
T}|T{
國立臺北大學 
T}
T{
 203\.64\.76
T}|T{
慈濟大學 
T}
T{
 203\.72\.73~87
T}|T{
慈濟大學 
T}
T{
 203\.64\.120
T}|T{
國立屏東商業技術學院 
T}
T{
 203\.64\.127
T}|T{
國立屏東商業技術學院 
T}
T{
 203\.64\.215
T}|T{
臺北城市科技大學 
T}
T{
 203\.68
T}|T{
國立高雄餐旅大學 
T}
T{
 203\.71\.84~88
T}|T{
臺北醫學大學 
T}
T{
 210\.70\.183
T}|T{
長榮大學 
T}
T{
 210\.71\.118
T}|T{
康寧大學 
T}
T{
 210\.60
T}|T{
德霖技術學院 
T}
T{
 211\.75\.81\.81
T}|T{
臺北基督學院 
T}
.TE
.SS 中等學校的 IP 範圍
.TS
tab(|) expand nowarn box;
 l l.
T{
ip
T}|T{
中學 
T}
_
T{
 210\.70\.70
T}|T{
台中高工 
T}
T{
 210\.70\.131
T}|T{
大安高工 
T}
T{
 210\.71\.78
T}|T{
建國中學 
T}
T{
 210\.60\.107
T}|T{
臺中一中 
T}
T{
 210\.60\.35
T}|T{
臺中一中 
T}
T{
 210\.60\.36
T}|T{
臺中一中 
T}
T{
 210\.70\.89
T}|T{
鳳山高中 
T}
T{
 210\.59\.2\.4
T}|T{
瑞芳高工 
T}
T{
 210\.70\.212
T}|T{
萬芳高中 
T}
T{
 163\.19\.116
T}|T{
建功高中 
T}
T{
 163\.23\.148
T}|T{
彰化高中 
T}
T{
 163\.32\.78
T}|T{
高雄高中 
T}
T{
 163\.32\.98
T}|T{
海青工商 
T}
T{
 163\.32\.84
T}|T{
三信家商 
T}
T{
 163\.26\.255
T}|T{
明達高中 
T}
T{
 203\.64\.161
T}|T{
板橋高中 
T}
T{
 203\.72\.181
T}|T{
中大附中 
T}
T{
 203\.71\.156
T}|T{
興大附中 
T}
T{
 203\.72\.57
T}|T{
市立大同高中 
T}
T{
 203\.72\.64
T}|T{
松山高中 
T}
T{
 140\.131\.145~149
T}|T{
師大附中 
T}
.TE
.SS 政府單位的 IP 範圍
.TS
tab(|) expand nowarn box;
 l l.
T{
ip
T}|T{
政府機關 
T}
_
T{
 192\.83\.186
T}|T{
國家圖書館 
T}
T{
 192\.192\.47\.50
T}|T{
國立公共資訊圖書館 
T}
T{
 203\.64\.154\.1
T}|T{
新北市立圖書館 
T}
T{
 203\.64\.188
T}|T{
國立教育廣播電臺 
T}
.TE
.SS 研究機構的 IP 範圍
.TS
tab(|) expand nowarn box;
 l l.
T{
研究機構
T}|T{
ip
T}
_
T{
140\.109
T}|T{
中央研究院 
T}
T{
192\.83\.168\.137
T}|T{
中華經濟研究院 
T}
.TE
.SS 來自 PTT 資料庫
.TS
tab(|) expand nowarn box;
 l l.
T{
ip
T}|T{
故鄉 
T}
_
T{
140\.112\.28\.0/22
T}|T{
台大資訊系
T}
T{
140\.112\.90\.0/23
T}|T{
台大資訊系
T}
T{
140\.112\.3\.0/23
T}|T{
台大計算機中心
T}
T{
140\.112\.6\.0/24
T}|T{
台大撥接/ADSL
T}
T{
140\.112\.7\.0/24
T}|T{
台大計中 PC 室
T}
T{
140\.112\.8\.0/24
T}|T{
台大計算機中心
T}
T{
140\.112\.10\.0/23
T}|T{
台大土木系
T}
T{
140\.112\.12\.0/23
T}|T{
台大土木系
T}
T{
140\.112\.14\.0/24
T}|T{
台大機械系
T}
T{
140\.112\.15\.0/24
T}|T{
台大志鴻館
T}
T{
140\.112\.16\.0/24
T}|T{
台大工綜
T}
T{
140\.112\.17\.0/24
T}|T{
台大電機系
T}
T{
140\.112\.18\.0/23
T}|T{
台大電機系
T}
T{
140\.112\.20\.0/23
T}|T{
台大電機系
T}
T{
140\.112\.41\.0/24
T}|T{
台大電機系
T}
T{
140\.112\.22\.0/23
T}|T{
台大化工系
T}
T{
140\.112\.25\.0/24
T}|T{
台大撥接/ADSL
T}
T{
140\.112\.26\.0/23
T}|T{
台大工科系
T}
T{
140\.112\.36\.0/24
T}|T{
台大工工所(工綜)
T}
T{
140\.112\.38\.0/23
T}|T{
台大應力所
T}
T{
140\.112\.40\.0/24
T}|T{
台大城鄉所
T}
T{
140\.112\.41\.0/24
T}|T{
台大電機系
T}
T{
140\.112\.42\.0/24
T}|T{
台大電機舊館
T}
T{
140\.112\.42\.0/24
T}|T{
台大電機舊館
T}
T{
140\.112\.43\.0/24
T}|T{
台大機械系
T}
T{
140\.112\.44\.0/24
T}|T{
台大機械系
T}
T{
140\.112\.46\.0/24
T}|T{
台大機械系
T}
T{
140\.112\.50\.0/24
T}|T{
台大數學館
T}
T{
140\.112\.52\.0/24
T}|T{
台大物理系
T}
T{
140\.112\.54\.0/24
T}|T{
台大化學系
T}
T{
140\.112\.56\.0/24
T}|T{
台大地質系
T}
T{
140\.112\.58\.0/24
T}|T{
台大動物系
T}
T{
140\.112\.60\.255/25
T}|T{
台大植物系
T}
T{
140\.112\.60\.0/24
T}|T{
台大植微系
T}
T{
140\.112\.61\.0/24
T}|T{
台大植研大樓
T}
T{
140\.112\.62\.0/24
T}|T{
台大心理系
T}
T{
140\.112\.64\.0/24
T}|T{
台大地理系
T}
T{
140\.112\.65\.0/24
T}|T{
台大全球變遷/凝態中心
T}
T{
140\.112\.66\.0/24
T}|T{
台大大氣系
T}
T{
140\.112\.67\.0/24
T}|T{
台大大氣系
T}
T{
140\.112\.68\.0/23
T}|T{
台大海洋所
T}
T{
140\.112\.70\.0/24
T}|T{
台大漁科所
T}
T{
140\.112\.72\.0/24
T}|T{
台大生化所
T}
T{
140\.112\.74\.0/24
T}|T{
台大農藝系
T}
T{
140\.112\.75\.0/24
T}|T{
台大生統教室
T}
T{
140\.112\.76\.0/24
T}|T{
台大生工系
T}
T{
140\.112\.78\.0/24
T}|T{
台大農化系
T}
T{
140\.112\.80\.0/24
T}|T{
台大植微系
T}
T{
140\.112\.81\.0/24
T}|T{
台大昆蟲館
T}
T{
140\.112\.82\.0/24
T}|T{
台大森林系
T}
T{
140\.112\.84\.0/24
T}|T{
台大畜產系
T}
T{
140\.112\.86\.0/24
T}|T{
台大農經系
T}
T{
140\.112\.88\.0/24
T}|T{
台大園藝系
T}
T{
140\.112\.89\.0/24
T}|T{
台大工廠
T}
T{
140\.112\.92\.0/24
T}|T{
台大農推系
T}
T{
140\.112\.94\.0/24
T}|T{
台大生機系
T}
T{
140\.112\.96\.0/24
T}|T{
台大獸醫系
T}
T{
140\.112\.99\.0/24
T}|T{
台大衛生組
T}
T{
140\.112\.100\.0/24
T}|T{
台大植病系養蟲館
T}
T{
140\.112\.106\.0/24
T}|T{
台大資管系
T}
T{
140\.112\.108\.0/24
T}|T{
台大管院計中
T}
T{
140\.112\.110\.0/24
T}|T{
台大管院計中
T}
T{
140\.112\.120\.0/24
T}|T{
台大醫學校區
T}
T{
140\.112\.122\.0/24
T}|T{
台大醫學院
T}
T{
140\.112\.136\.0/24
T}|T{
台大公衛系
T}
T{
140\.112\.141\.0/24
T}|T{
台大中文系/外文系
T}
T{
140\.112\.142\.0/24
T}|T{
台大歷史系/藝術史所
T}
T{
140\.112\.143\.0/24
T}|T{
台大哲學系/農業陳列館
T}
T{
140\.112\.145\.0/24
T}|T{
台大闈場及普通教室
T}
T{
140\.112\.146\.0/24
T}|T{
台大日文系/戲劇所/語言所
T}
T{
140\.112\.150\.0/24
T}|T{
台大法學院/法圖
T}
T{
140\.112\.153\.0/24
T}|T{
台大新聞所
T}
T{
140\.112\.155\.0/24
T}|T{
台大國家發展所
T}
T{
140\.112\.156\.0/24
T}|T{
台大社會系
T}
T{
140\.112\.157\.0/24
T}|T{
台大社會系
T}
T{
140\.112\.160\.0/24
T}|T{
台大行政大樓
T}
T{
140\.112\.169\.0/24
T}|T{
台大研二小套房
T}
T{
140\.112\.170\.0/24
T}|T{
台大研二中套房
T}
T{
140\.112\.171\.0/24
T}|T{
台大研二大套房
T}
T{
140\.112\.173\.0/24
T}|T{
台大女八快餐店
T}
T{
140\.112\.178\.0/24
T}|T{
台大學生住宿服務組
T}
T{
140\.112\.181\.0/24
T}|T{
台大管理學院
T}
T{
140\.112\.182\.0/24
T}|T{
台大工綜
T}
T{
140\.112\.183\.0/24
T}|T{
台大農業自動化教室
T}
T{
140\.112\.193\.0/24
T}|T{
台大女九紗棉坊
T}
T{
140\.112\.195\.0/24
T}|T{
台大數化舍
T}
T{
140\.112\.201\.0/24
T}|T{
台大東亞文明研究中心
T}
T{
140\.112\.204\.0/24
T}|T{
台大女四小木屋
T}
T{
140\.112\.205\.0/24
T}|T{
台大 ADSL
T}
T{
140\.112\.211\.0/24
T}|T{
台大男四舍
T}
T{
140\.112\.212\.0/24
T}|T{
台大男二館
T}
T{
140\.112\.213\.0/24
T}|T{
台大男二館
T}
T{
140\.112\.214\.0/24
T}|T{
台大男四舍
T}
T{
140\.112\.215\.0/24
T}|T{
台大男 16 舍
T}
T{
140\.112\.216\.0/24
T}|T{
台大女三甜蜜窩
T}
T{
140\.112\.217\.0/24
T}|T{
台大水源宿舍
T}
T{
140\.112\.218\.0/24
T}|T{
台大水源宿舍
T}
T{
140\.112\.220\.0/24
T}|T{
台大女一小閨房
T}
T{
140\.112\.221\.0/24
T}|T{
台大女一大閨房
T}
T{
140\.112\.222\.0/24
T}|T{
台大女二手工舖
T}
T{
140\.112\.223\.0/24
T}|T{
台大女三甜蜜窩
T}
T{
140\.112\.224\.0/24
T}|T{
台大女七成衣場
T}
T{
140\.112\.225\.0/24
T}|T{
台大女五針織室
T}
T{
140\.112\.226\.0/24
T}|T{
台大女六婚紗廊
T}
T{
140\.112\.227\.0/24
T}|T{
台大女七成衣場
T}
T{
140\.112\.228\.0/24
T}|T{
台大女二手工舖
T}
T{
140\.112\.229\.0/24
T}|T{
台大國青宿舍
T}
T{
140\.112\.231\.0/24
T}|T{
台大國青宿舍
T}
T{
140\.112\.232\.0/24
T}|T{
台大國青宿舍
T}
T{
140\.112\.233\.0/24
T}|T{
台大研一舍
T}
T{
140\.112\.234\.0/24
T}|T{
台大研一舍
T}
T{
140\.112\.239\.0/24
T}|T{
台大男一窩
T}
T{
140\.112\.240\.0/23
T}|T{
台大男一窩
T}
T{
140\.112\.242\.0/24
T}|T{
台大男一窩
T}
T{
140\.112\.242\.0/24
T}|T{
台大男一窩
T}
T{
140\.112\.243\.0/24
T}|T{
台大男三屋
T}
T{
140\.112\.244\.0/24
T}|T{
台大男三屋
T}
T{
140\.112\.245\.0/24
T}|T{
台大男五房
T}
T{
140\.112\.246\.0/24
T}|T{
台大男五房
T}
T{
140\.112\.247\.0/24
T}|T{
台大男六眷
T}
T{
140\.112\.248\.0/24
T}|T{
台大男六眷
T}
T{
140\.112\.249\.0/24
T}|T{
台大男七窯
T}
T{
140\.112\.250\.0/24
T}|T{
台大男七窯
T}
T{
140\.112\.251\.0/24
T}|T{
台大男八別墅
T}
T{
140\.112\.252\.0/24
T}|T{
台大男八別墅
T}
T{
140\.112\.253\.0/24
T}|T{
台大男八別墅
T}
T{
140\.112\.0\.0/16
T}|T{
台灣大學
T}
T{
140\.109\.0\.0/16
T}|T{
中央研究院
T}
T{
140\.111\.76\.0/24
T}|T{
宜大男生宿舍
T}
T{
140\.111\.78\.0/24
T}|T{
宜大女生宿舍
T}
T{
140\.111\.73\.0/24
T}|T{
國立宜蘭大學
T}
T{
140\.111\.79\.0/24
T}|T{
國立宜蘭大學
T}
T{
140\.111\.0\.0/16
T}|T{
教育部
T}
T{
140\.113\.0\.0/16
T}|T{
交通大學
T}
T{
140\.114\.0\.0/16
T}|T{
清華大學
T}
T{
140\.115\.81\.0/24
T}|T{
中央大學管理學院
T}
T{
140\.115\.83\.0/24
T}|T{
中央大學管理學院
T}
T{
140\.115\.84\.0/24
T}|T{
中央大學管理學院
T}
T{
140\.115\.85\.0/24
T}|T{
中央大學產經所
T}
T{
140\.115\.0\.0/16
T}|T{
中央大學
T}
T{
140\.116\.0\.0/16
T}|T{
成功大學
T}
T{
140\.117\.0\.0/16
T}|T{
中山大學
T}
T{
140\.118\.0\.0/16
T}|T{
台灣科技大學
T}
T{
140\.119\.0\.0/16
T}|T{
政治大學
T}
T{
140\.120\.0\.0/16
T}|T{
中興大學
T}
T{
140\.121\.0\.0/16
T}|T{
海洋大學
T}
T{
140\.122\.0\.0/16
T}|T{
台灣師範大學
T}
T{
140\.123\.0\.0/16
T}|T{
中正大學
T}
T{
140\.124\.0\.0/16
T}|T{
台北科技大學
T}
T{
140\.125\.0\.0/16
T}|T{
雲林科技大學
T}
T{
140\.126\.2\.0/23
T}|T{
中華大學
T}
T{
140\.126\.32\.0/20
T}|T{
新竹師範學院
T}
T{
140\.127\.112\.0/24
T}|T{
高雄應用科技大學
T}
T{
140\.127\.113\.0/24
T}|T{
高雄應用科技大學
T}
T{
140\.127\.114\.0/24
T}|T{
高雄應用科技大學
T}
T{
140\.127\.150\.0/24
T}|T{
高雄應用科技大學
T}
T{
140\.127\.38\.0/24
T}|T{
高雄師範大學
T}
T{
140\.127\.45\.0/24
T}|T{
高雄師範大學
T}
T{
140\.127\.54\.0/24
T}|T{
高雄師範大學
T}
T{
140\.127\.81\.0/21
T}|T{
屏東教育大學
T}
T{
140\.127\.64\.0/18
T}|T{
高雄師範大學
T}
T{
140\.127\.128\.0/19
T}|T{
義守大學
T}
T{
140\.127\.0\.0/19
T}|T{
高雄大學
T}
T{
140\.128\.61\.0/24
T}|T{
中國醫藥大學
T}
T{
140\.128\.136\.0/24
T}|T{
中山醫學大學
T}
T{
140\.128\.138\.0/24
T}|T{
中山醫學大學
T}
T{
140\.128\.71\.0/24
T}|T{
勤益技術學院
T}
T{
140\.128\.72\.0/20
T}|T{
勤益技術學院
T}
T{
140\.128\.80\.0/19
T}|T{
勤益技術學院
T}
T{
140\.128\.0\.0/16
T}|T{
東海大學
T}
T{
140\.129\.37\.0/24
T}|T{
大同大學
T}
T{
140\.129\.38\.0/24
T}|T{
大同大學
T}
T{
140\.129\.39\.0/24
T}|T{
大同大學
T}
T{
140\.129\.40\.0/24
T}|T{
大同大學
T}
T{
140\.129\.41\.0/24
T}|T{
大同大學
T}
T{
140\.129\.42\.0/24
T}|T{
大同大學
T}
T{
140\.129\.56\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.57\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.58\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.59\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.60\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.61\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.62\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.63\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.68\.0/24
T}|T{
陽明大學牙醫館
T}
T{
140\.129\.79\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.164\.0/24
T}|T{
陽明大學
T}
T{
140\.129\.165\.0/24
T}|T{
陽明大學
T}
T{
140\.130\.0\.0/16
T}|T{
嘉義大學
T}
T{
140\.131\.15\.0/20
T}|T{
龍華科技大學
T}
T{
140\.131\.16\.0/24
T}|T{
龍華科技大學
T}
T{
140\.131\.17\.0/24
T}|T{
龍華科技大學
T}
T{
140\.131\.18\.0/24
T}|T{
龍華科技大學
T}
T{
140\.131\.19\.0/24
T}|T{
龍華科技大學
T}
T{
140\.131\.20\.0/24
T}|T{
龍華科技大學
T}
T{
140\.131\.30\.0/24
T}|T{
台灣藝術大學
T}
T{
140\.131\.0\.0/16
T}|T{
銘傳大學
T}
T{
140\.132\.0\.0/16
T}|T{
中正理工學院
T}
T{
140\.134\.0\.0/16
T}|T{
逢甲大學
T}
T{
140\.135\.0\.0/16
T}|T{
中原大學
T}
T{
140\.136\.0\.0/16
T}|T{
輔仁大學
T}
T{
140\.137\.0\.0/16
T}|T{
文化大學
T}
T{
140\.138\.0\.0/16
T}|T{
元智大學
T}
T{
163\.13\.0\.0/16
T}|T{
淡江大學
T}
T{
163\.14\.0\.0/16
T}|T{
東吳大學
T}
T{
163\.15\.0\.0/16
T}|T{
高雄醫學大學
T}
T{
163\.24\.241\.0/20
T}|T{
屏東教育大學
T}
T{
163\.25\.0\.0/16
T}|T{
長庚大學
T}
T{
192\.83\.191\.0/24
T}|T{
義守大學
T}
T{
192\.192\.35\.0/24
T}|T{
台北大學
T}
T{
192\.192\.36\.0/24
T}|T{
台北大學
T}
T{
192\.192\.90\.0/24
T}|T{
國防大學國防醫學院
T}
T{
192\.192\.197\.0/24
T}|T{
長榮大學
T}
T{
192\.192\.198\.0/24
T}|T{
長榮大學
T}
T{
192\.192\.199\.0/24
T}|T{
長榮大學
T}
T{
203\.64\.3\.0/24
T}|T{
國立藝術學院
T}
T{
203\.68\.128\.0/17
T}|T{
台北大學
T}
T{
203\.71\.112\.0/22
T}|T{
長榮大學
T}
T{
203\.71\.116\.0/23
T}|T{
長榮大學
T}
T{
210\.60\.180\.0/20
T}|T{
義守大學
T}
T{
210\.70\.145\.0/24
T}|T{
長榮大學
T}
T{
210\.70\.146\.0/23
T}|T{
長榮大學
T}
T{
210\.70\.148\.0/22
T}|T{
長榮大學
T}
T{
210\.70\.152\.0/21
T}|T{
長榮大學
T}
T{
210\.70\.160\.0/20
T}|T{
長榮大學
T}
T{
210\.70\.176\.0/21
T}|T{
長榮大學
T}
T{
210\.240\.172\.0/24
T}|T{
台東大學
T}
T{
203\.64\.26\.0/24
T}|T{
建國中學
T}
T{
210\.71\.78\.0/24
T}|T{
建國中學
T}
T{
210\.59\.53\.0/24
T}|T{
國立中和高中
T}
T{
210\.60\.107\.0/24
T}|T{
國立台中一中
T}
T{
59\.104\.0\.0/15
T}|T{
SeedNet
T}
T{
59\.112\.0\.0/16
T}|T{
HiNet
T}
T{
61\.13\.0\.0/16
T}|T{
英普達寬頻
T}
T{
61\.16\.0\.0/16
T}|T{
英普達寬頻
T}
T{
61\.30\.0\.0/16
T}|T{
台灣固網
T}
T{
61\.31\.0\.0/16
T}|T{
台灣固網
T}
T{
61\.56\.128\.0/20
T}|T{
So\-net
T}
T{
61\.59\.0\.0/16
T}|T{
種子寬頻
T}
T{
61\.62\.0\.0/16
T}|T{
So\-net
T}
T{
61\.63\.160\.0/19
T}|T{
@corner
T}
T{
61\.63\.192\.0/18
T}|T{
@corner
T}
T{
61\.64\.0\.0/16
T}|T{
So\-net
T}
T{
61\.70\.0\.0/16
T}|T{
Giga 超網路
T}
T{
61\.71\.0\.0/16
T}|T{
Giga 超網路
T}
T{
61\.216\.0\.0/13
T}|T{
HiNet 寬頻
T}
T{
61\.224\.0\.0/13
T}|T{
HiNet
T}
T{
139\.175\.0\.0/16
T}|T{
SeedNet
T}
T{
163\.30\.0\.0/16
T}|T{
HiNet
T}
T{
163\.31\.0\.0/16
T}|T{
HiNet
T}
T{
163\.32\.0\.0/16
T}|T{
HiNet
T}
T{
168\.95\.0\.0/16
T}|T{
HiNet
T}
T{
202\.178\.0\.0/16
T}|T{
東森寬頻
T}
T{
203\.64\.26\.0/24
T}|T{
建國中學
T}
T{
203\.73\.0\.0/16
T}|T{
種子寬頻
T}
T{
203\.133\.0\.0/16
T}|T{
Giga 超網路
T}
T{
203\.203\.0\.0/16
T}|T{
Giga 寬頻
T}
T{
203\.204\.0\.0/16
T}|T{
Giga 寬頻
T}
T{
210\.58\.0\.0/16
T}|T{
東森寬頻
T}
T{
210\.64\.0\.0/16
T}|T{
種子寬頻
T}
T{
210\.66\.0\.0/16
T}|T{
種子寬頻
T}
T{
210\.68\.0\.0/16
T}|T{
種子寬頻
T}
T{
210\.71\.78\.0/24
T}|T{
建國中學
T}
T{
211\.74\.128\.0/17
T}|T{
種子寬頻
T}
T{
211\.75\.0\.0/17
T}|T{
HiNet
T}
T{
211\.76\.32\.0/19
T}|T{
聯宇寬頻
T}
T{
211\.78\.0\.0/16
T}|T{
台灣固網
T}
T{
210\.85\.0\.0/16
T}|T{
東森寬頻
T}
T{
210\.59\.53\.0/24
T}|T{
國立中和高中
T}
T{
210\.60\.107\.0/24
T}|T{
國立台中一中
T}
T{
210\.201\.0\.0/16
T}|T{
亞太線上
T}
T{
210\.202\.0\.0/16
T}|T{
東森寬頻
T}
T{
210\.208\.0\.0/16
T}|T{
SayHiNet 無限撥接
T}
T{
211\.74\.0\.0/24
T}|T{
種子寬頻
T}
T{
218\.160\.0\.0/12
T}|T{
HiNet 寬頻
T}
T{
218\.32\.0\.0/16
T}|T{
速博網
T}
T{
218\.34\.0\.0/15
T}|T{
亞太寬頻
T}
T{
211\.78\.0\.0/16
T}|T{
台灣固網
T}
T{
218\.184\.0\.0/16
T}|T{
東森寬頻
T}
T{
218\.187\.0\.0/16
T}|T{
亞太線上
T}
T{
219\.68\.0\.0/14
T}|T{
Giga 超網路
T}
T{
219\.80\.0\.0/16
T}|T{
台灣固網
T}
T{
219\.81\.0\.0/16
T}|T{
台灣固網
T}
T{
219\.91\.0\.0/17
T}|T{
亞太線上
T}
T{
220\.129\.0\.0/16
T}|T{
HiNet
T}
T{
220\.130\.0\.0/15
T}|T{
HiNet
T}
T{
220\.132\.0\.0/14
T}|T{
HiNet
T}
T{
220\.136\.0\.0/13
T}|T{
HiNet
T}
.TE
.SS 個人補充：
.TS
tab(|) expand nowarn box;
 l l.
T{
ip
T}|T{
單位
T}
_
T{
203\.64\.138\.1
T}|T{
成功高中 （母校！）
T}
T{
168\.95\.1\.1
T}|T{
中華電信 DNS（如果這東西掛了，大概全台灣都掛了。）
T}
T{
8\.8\.8\.8
T}|T{
google DNS（如果這東西掛了，大概全世界都掛了。）
T}
T{
203\.72\.0~6
T}|T{
南華大學
T}
T{
201\.59\.110~123
T}|T{
華梵大學
T}
T{
140\.110
T}|T{
國網中心
T}
T{
163\.21\.208
T}|T{
麗山高中
T}
.TE
.SH 參考文獻
.RS 0
.IP 1. 3
台灣學術網路(TANet)概述\.
.IP 2. 3
台灣學術網路(TANet)概述\.
教育部資訊及科技教育司\. [2015\-01\-26]
（中文（台灣））\.
.IP 3. 3
台灣網際網路發展史編撰研究計畫
http://www\.twnic\.net\.tw/download/ip\-94\-1\.pdf
.IP 4. 3
林信成\. 《INTERNET 全民上網大探索》\. 第三波\. ISBN 9572304488\.
.IP 5. 3
台灣學術網路(TANet)骨幹架構圖

.RE
.SH 外部連結
.RS 0
.IP \(bu 2
TANet 維運中心
.IP \(bu 2
台灣學術網路運作
.IP \(bu 2
TANet 無線網路漫遊交換中心
.IP \(bu 2
各縣市教育網路中心連結列表
.IP \(bu 2
台灣學術網路危機處理中心
.IP \(bu 2
台灣學術網路(TANET)\-不當資訊過濾防制系統營運服務
.IP \(bu 2
台灣學術網路校園語音交換平台]
.IP \(bu 2
歷年台灣學術網路演進
.IP \(bu 2
TWAREN 網路

.RE
.SH 維基百科授權聲明
.P
本站的全部文字在知识共享 署名\-相同方式共享
3\.0 协议之条款下提供，附加条款亦可能应用。（请参阅使用条款）
Wikipedia®和维基百科标志是维基媒体基金会的注册商标；
维基™是维基媒体基金会的商标。
维基媒体基金会是在美国佛罗里达州登记的 501(c)(3)
免税、非营利、慈善机构。
