#!/usr/bin/bash

TRASH="$HOME/.local/trash"
if [ -d "$TRASH" ] ; then
    :
else
    echo "trash can \"$TRASH\" doesn't exist!">&2
    exit 1
fi

for file in $@ ; do

    new_name="$file"

    while [ -a "$TRASH/$new_name" ] ; do
        new_name="${new_name}_"
    done

    mv "$file" "$TRASH/$new_name"

done

